services:
  queue:
    image: rabbitmq:3.9-rc-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  gateway:
    build:
      context: ./gateway
    volumes:
      - ./gateway:/app
      - /app/node_modules
    ports:
      - 5000:5000
  wilders:
    build:
      context: ./wilders
    volumes:
      - ./wilders:/app
      - /app/node_modules
  skills:
    build:
      context: ./skills
    volumes:
      - ./skills:/app
      - /app/node_modules
