services:
  queue:
    image: rabbitmq:3.9-rc-management-alpine
    ports:
      - 15672:15672
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  gateway:
    build:
      context: ./gateway
    volumes:
      - ./gateway/src:/app/src
    ports:
      - 5000:5000
  wilders:
    build:
      context: ./wilders
    volumes:
      - ./wilders/src:/app/src
  skills:
    build:
      context: ./skills
    volumes:
      - ./skills/src:/app/src
